In [1]:
import pandas as pd
import numpy as np
import os

# Display settings
pd.set_option("display.max_columns", None)

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
sales_df = pd.read_csv("sales_data.csv")
churn_df = pd.read_csv("customer_churn.csv")
house_df = pd.read_csv("house_prices.csv")

print("Datasets loaded successfully")

Datasets loaded successfully

In [3]:
print("SALES DATA")
display(sales_df.head())
print(sales_df.info())

SALES DATA

         Date     Product  Quantity  Price Customer_ID Region  Total_Sales
0  2024-01-01       Phone         7  37300     CUST001   East       261100
1  2024-01-02  Headphones         4  15406     CUST002  North        61624
2  2024-01-03       Phone         2  21746     CUST003   West        43492
3  2024-01-04  Headphones         1  30895     CUST004   East        30895
4  2024-01-05      Laptop         8  39835     CUST005  North       318680

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         100 non-null    object
 1   Product      100 non-null    object
 2   Quantity     100 non-null    int64
 3   Price        100 non-null    int64
 4   Customer_ID  100 non-null    object
 5   Region       100 non-null    object
 6   Total_Sales  100 non-null    int64
dtypes: int64(3), object(4)
memory usage: 5.6+ KB
None

In [4]:
print("CUSTOMER CHURN DATA")
display(churn_df.head())
print(churn_df.info())

CUSTOMER CHURN DATA

,CustomerID,Tenure,MonthlyCharges,TotalCharges,Contract,PaymentMethod,PaperlessBilling,SeniorCitizen,Churn
0,C00001,6,64,1540,One year,Credit Card,No,1,0
1,C00002,21,113,1753,Month-to-month,Electronic Check,Yes,1,0
2,C00003,27,31,1455,Two year,Credit Card,No,1,0
3,C00004,53,29,7150,Month-to-month,Electronic Check,No,1,0
4,C00005,16,185,1023,One year,Electronic Check,No,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        500 non-null    object
 1   Tenure            500 non-null    int64
 2   MonthlyCharges    500 non-null    int64
 3   TotalCharges      500 non-null    int64
 4   Contract          500 non-null    object
 5   PaymentMethod     500 non-null    object
 6   PaperlessBilling  500 non-null    object
 7   SeniorCitizen     500 non-null    int64
 8   Churn             500 non-null    int64
dtypes: int64(5), object(4)
memory usage: 35.3+ KB
None

In [5]:
print("HOUSE PRICES DATA")
display(house_df.head())
print(house_df.info())

HOUSE PRICES DATA

,Property_ID,Area,Bedrooms,Bathrooms,Age,Location,Property_Type,Price
0,PROP0001,3712,4,3,36,Rural,House,22260000
1,PROP0002,1591,4,1,35,Suburb,House,16057500
2,PROP0003,1646,4,3,20,Rural,Villa,12730000
3,PROP0004,4814,1,2,13,City Center,Villa,50840000
4,PROP0005,800,4,2,38,Suburb,Apartment,10650000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Property_ID    300 non-null    object
 1   Area           300 non-null    int64
 2   Bedrooms       300 non-null    int64
 3   Bathrooms      300 non-null    int64
 4   Age            300 non-null    int64
 5   Location       300 non-null    object
 6   Property_Type  300 non-null    object
 7   Price          300 non-null    int64
dtypes: int64(5), object(3)
memory usage: 18.9+ KB
None

In [6]:
print("Sales Missing Values")
print(sales_df.isnull().sum())

print("\nChurn Missing Values")
print(churn_df.isnull().sum())

print("\nHouse Prices Missing Values")
print(house_df.isnull().sum())

Sales Missing Values
Date           0
Product        0
Quantity       0
Price          0
Customer_ID    0
Region         0
Total_Sales    0
dtype: int64

Churn Missing Values
CustomerID          0
Tenure              0
MonthlyCharges      0
TotalCharges        0
Contract            0
PaymentMethod       0
PaperlessBilling    0
SeniorCitizen       0
Churn               0
dtype: int64

House Prices Missing Values
Property_ID      0
Area             0
Bedrooms         0
Bathrooms        0
Age              0
Location         0
Property_Type    0
Price            0
dtype: int64

In [7]:
def clean_numeric(df):
    num_cols = df.select_dtypes(include=['int64','float64']).columns
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())
    return df

def clean_categorical(df):
    cat_cols = df.select_dtypes(include=['object']).columns
    for col in cat_cols:
        df[col].fillna(df[col].mode()[0], inplace=True)
    return df

In [8]:
sales_df = clean_numeric(sales_df)
sales_df = clean_categorical(sales_df)

churn_df = clean_numeric(churn_df)
churn_df = clean_categorical(churn_df)

house_df = clean_numeric(house_df)
house_df = clean_categorical(house_df)

print("Missing values handled")

Missing values handled

In [9]:
sales_df.drop_duplicates(inplace=True)
churn_df.drop_duplicates(inplace=True)
house_df.drop_duplicates(inplace=True)

print("Duplicates removed")

Duplicates removed

In [ ]:

if {'Quantity', 'Price'}.issubset(sales_df.columns):
    sales_df["Total_Sales"] = sales_df["Quantity"] * sales_df["Price"]

print("Feature engineering completed")

Feature engineering completed

In [11]:
print("Sales Shape:", sales_df.shape)
print("Churn Shape:", churn_df.shape)
print("House Shape:", house_df.shape)

print("Cleaning validation done")

Sales Shape: (100, 7)
Churn Shape: (500, 9)
House Shape: (300, 8)
Cleaning validation done

In [13]:
sales_df.to_csv("cleaned_sales_data.csv", index=False)
churn_df.to_csv("cleaned_customer_churn.csv", index=False)
house_df.to_csv("cleaned_house_prices.csv", index=False)

print("Cleaned datasets saved successfully")

Cleaned datasets saved successfully